services:
  - type: web
    name: kazpartybot
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: KASPI_NAME
        sync: false
